const {chromium, firefox, webkit} = require('/home/codex/tools/browser-tests/node_modules/playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const {createServer} = require('node:http');
const path = require('node:path');
let origin = process.env.UO_URL;
let server;
const output = 'test-results/copy-verification';
fs.mkdirSync(output, {recursive:true});
const chart = fs.readFileSync('js/vendor/chart.umd.js');

(async () => {
 if (!origin) {
  const root=process.env.UO_ROOT || path.resolve(__dirname,'..');
  server=createServer((req,res)=>{
   const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0] === '/' ? '/index.html' : req.url.split('?')[0]));
   if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}
   const types={'.js':'application/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.pdf':'application/pdf'};
   res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  origin='http://127.0.0.1:'+server.address().port;
 }
 for (const [engine, launcher] of Object.entries({chromium, firefox, webkit})) {
  if(process.env.BROWSERS && !process.env.BROWSERS.split(',').includes(engine)) continue;
  const browser = await launcher.launch({headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  await context.route('https://cdn.jsdelivr.net/npm/chart.js', route => route.fulfill({contentType:'application/javascript',body:chart}));
  await context.route('**/__preview_revision', route => route.fulfill({json:{revision:'test'}}));
  const page = await context.newPage();
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('response',response=>{if(response.status()>=400 && response.url().startsWith(origin)) errors.push(`${response.status()} ${response.url()}`);});
  await page.goto(origin);
  await page.waitForFunction(()=>typeof state !== 'undefined' && state.searchWorkerReady && document.querySelectorAll('.card').length > 0);
  assert.equal(await page.locator('h1').innerText(), 'UO Salary Transparency');
  assert.equal(await page.locator('#stat-total').innerText(), '6,289');
  await page.screenshot({path:`${output}/${engine}-desktop.png`});
  await page.locator('#historical-toggle').click();
  await page.waitForFunction(()=>Object.keys(state.historicalCharts).length === 5);
  await page.locator('#historical-advanced-toggle').click();
  await page.waitForFunction(()=>Object.keys(state.historicalCharts).length === 14);
  console.log(engine, 'historical charts', await page.evaluate(()=>Object.keys(state.historicalCharts)));
  await page.locator('#historical-charts').screenshot({path:`${output}/${engine}-charts.png`});
  await page.locator('#historical-toggle').click();
  await page.locator('#advanced-toggle').click();
  await page.locator('#search').fill('/^abshere,/i');
  await page.waitForFunction(()=>state.filteredKeys?.length > 0 && state.filteredKeys.every(n=>n.toLowerCase().includes('abshere')));
  const visible = await page.locator('.card').first().getAttribute('data-name');
  await page.locator('.card-header').first().click();
  await page.waitForSelector('.history[data-loaded="true"]');
  await page.waitForFunction(()=>Object.keys(state.personCharts).length > 0);
  const history = await page.locator('.history').first().textContent();
  assert.ok(history.includes('Not supplied'));
  assert.ok(await page.locator('.source-report-link').count()>0);
  const href=await page.locator('.source-report-link').first().getAttribute('href');
  assert.ok(href.includes('#page='));
  const reportResponse=await context.request.get(new URL(href, origin).href);
  assert.equal(reportResponse.status(),200);
  await page.locator('.card').first().screenshot({path:`${output}/${engine}-person.png`});
  await page.locator('#search').fill('pay:60k-90k type:classified');
  await page.waitForFunction(()=>state.filteredKeys.length>0 && state.filteredKeys.every(n=>!state.masterData[n]._isUnclass && state.masterData[n]._totalPay >= 60000 && state.masterData[n]._totalPay <= 90000));
  await page.locator('#search').fill('');
  await page.waitForFunction(()=>state.filteredKeys.length===6289);
  await page.locator('#show-inactive').check();
  await page.waitForFunction(()=>state.filteredKeys.length===24223);
  await page.locator('#show-inactive').uncheck();
  await page.locator('#type-filter').selectOption('classified');
  await page.waitForFunction(()=>state.filteredKeys.length>0 && state.filteredKeys.every(n=>!state.masterData[n]._isUnclass));
  await page.locator('#type-filter').selectOption('all');
  await page.locator('#pay-measure').selectOption('fiscal_year_pay');
  await page.waitForFunction(()=>typeof PAY_MEASURE !== 'undefined' && PAY_MEASURE==='fiscal_year_pay' && state.searchWorkerReady && state.filteredKeys.length===7100);
  assert.equal(await page.locator('#fte-toggle').isDisabled(),true);
  await page.locator('.card-header').first().click();
  await page.waitForSelector('.history[data-loaded="true"]');
  assert.ok((await page.locator('.history').first().textContent()).includes('fiscal year'));
  await page.screenshot({path:`${output}/${engine}-actual-pay.png`});
  await page.goto(origin+'/records.html');
  await page.waitForSelector('.record-card');
  assert.equal(await page.locator('.record-card').count(),93);
  await page.locator('[data-filter="Classified"]').click();
  assert.equal(await page.locator('.record-card').count(),47);
  await page.goto(origin+'/inflation.html');
  await page.waitForSelector('tbody tr');
  await page.goto(origin+'/upper-middle-mang-report.html');
  await page.waitForFunction(()=>document.querySelector('#latest-headcount').textContent === '974');
  assert.ok((await page.locator('#load-status').textContent()).includes('validated aggregate'));
  await page.setViewportSize({width:390,height:844});
  await page.goto(origin);
  await page.waitForSelector('.card');
  await page.screenshot({path:`${output}/${engine}-mobile.png`});
  await page.locator('#advanced-toggle').click();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert.equal(overflow,false,'Mobile advanced controls overflow');
  await page.locator('#info-btn').click();
  assert.equal(await page.locator('#info-modal').isVisible(),true);
  await page.locator('#close-modal').click();
  // Exercise the copied main-thread fallback without a worker.
  const fallback=await context.newPage();
  await fallback.addInitScript(()=>{window.Worker=undefined;});
  await fallback.goto(origin+'/?q=abshere');
  await fallback.waitForSelector('.card');
  assert.ok((await fallback.locator('.card').first().textContent()).toLowerCase().includes('abshere'));
  assert.deepEqual(errors,[]);
  console.log(engine,'PASS',visible);
  await browser.close();
 }
 if(server) server.close();
})().catch(error=>{console.error(error);if(server)server.close();process.exit(1);});
